### PR TITLE
Foxblaster demystification and Lgun decomp

### PR DESCRIPTION
**Pull request by AaronB-Hub**

### CODE REVIEW

**Comment by ribbanya** [comment]
Nice documentation!

**Comment by AaronB-Hub** [comment]
Can that failure be ignored or do I need to fix?

**Comment by AaronB-Hub** [comment]
If it's an issue, I think I know what the cause is

**Comment by ribbanya** [comment]
Yeah sorry, I just hadn't had a chance to look at it. If it's in the same file it's fine.

**Comment by AaronB-Hub** [comment]
No worries! Figured it'd wait until after the workday :)

**Pull request merged**
