### PR TITLE
Match ~79% of hammer item

### PR DESCRIPTION
**Pull request by ItzSwirlz**
src: https://decomp.me/scratch/nF6aS

### CODE REVIEW

**Review by ribbanya — CHANGES_REQUESTED** [review]
This needs the asm for non-matching functions to be migrated to C and then the C surrounded in `#if` blocks. I can do it today or tomorrow probably.

**Comment by jpeisach** [comment]
It includes everything, the non-matching functions/the ones that cause compilation errors have the bad lines commenteed

**Comment by jpeisach** [comment]
I found a few things actually hold on

**Comment by RevoSucks** [comment]
update on this?

**Comment by jpeisach** [comment]
yeah it's down to a register swap

**Comment by jpeisach** [comment]
https://decomp.me/scratch/Q1rJA very close

**Comment by r-burns** [comment]
Unless I'm missing something I don't see any regswaps in that scratch. I do see some mis-scheduled epilogues, but I bet those will match with our new 1.2.5n compiler. So if that scratch is the whole file I think you have a 100% match, nice!

**Comment by ribbanya** [comment]
> I bet those will match with our new 1.2.5n compiler

https://decomp.me/scratch/Xaf1U

**Comment by PsiLupan** [comment]
Closing in favor of updated PR that I've created that also matches data.

**Pull request closed without merging**
