### PR TITLE
Change github actions from wine to wibo

### PR DESCRIPTION
**Pull request by BR-**
Not sure if this will work, but worth trying to get rid of the spurious wine failures.

### CODE REVIEW

**Comment by BR-** [comment]
Don't merge this yet.

**Comment by BR-** [comment]
Ready to merge! As a bonus it'll output the current match % and upload the map file on successful builds.

**Comment by BR-** [comment]
WiBo is about to switch from Makefile to CMake. As that'll break this PR, I'll fix and reopen this once it's ready.

**Comment by r-burns** [comment]
I think you have to explicitly link the filesystem library on gcc 8. Try adding -lstdc++fs to LDFLAGS

**Comment by BR-** [comment]
Yeah, I added that for the makefile but now it was lost in the transition to cmake. Going to PR it on the wibo side.

**Comment by r-burns** [comment]
I don't think that should be PR'd upstream since it's a peculiarity of certain older gcc versions, modern compilers don't need this. At the very least it should be conditional on the result of a try_compile.

**Comment by r-burns** [comment]
Does the linker error only show up when compiled with optimizations? You could try to cmake build in Debug mode to check.

**Comment by BR-** [comment]
Hopefully good to merge. If the patch is bad we'll find out sooner or later with testing. Not like we can do much worse than the current wine setup.

EDIT: oop, left WIBO_DEBUG on by default. removed

**Pull request merged**
