### PR TITLE
Fix editorconfig workflow

### PR DESCRIPTION
**Pull request by ribbanya**
Applies https://github.com/NixOS/nixpkgs/commit/31ce09b37790915618e839ed6a728f7b40157fdc.

### CODE REVIEW

**Comment by ribbanya** [comment]
Okay well that didn't work. I would really prefer to have a container so this doesn't happen again.

**Comment by ribbanya** [comment]
This PR is running master's workflow so I don't actually know how to test this.

**Review by r-burns — APPROVED** [review]

**Comment by ribbanya** [comment]
Going with #747.

**Comment by r-burns** [comment]
Why? This change is tiny and will fix it.

**Comment by ribbanya** [comment]
I don't want to rely on a package manager that randomly breaks stuff. The container image is the same hash every time.

**Comment by r-burns** [comment]
If you'd rather pin to a specific version you can do it like this https://github.com/nix-community/home-manager/commit/9438e56a7b7df5e02091027dccdd8d86768f1a2d

**Comment by ribbanya** [comment]
I'm just not going to use Nix for CI.

**Comment by r-burns** [comment]
I think you are overreacting to a very small breakage.

**Comment by ribbanya** [comment]
Possibly. But in this instance you had to use your preexisting Nix knowledge to find the patch whereas "download exe with hash and run it" is something everyone understands and it will work until GitHub shuts down.

**Comment by r-burns** [comment]
I didn't use any nix knowledge, I just looked at upstream nixpkgs for the fix.

**Comment by ribbanya** [comment]
Okay well I don't think this is going anywhere productive. Please choose one of the PRs and merge it.

**Review by ribbanya — COMMENTED** [review]
Can we add the `GITHUB_STEP_SUMMARY` stuff from #747?

**Pull request merged**
