### PR TITLE
RObj match

### PR DESCRIPTION
**Pull request by PsiLupan**

### CODE REVIEW

**Comment by ribbanya** [comment]
@PsiLupan How would you feel about merging with [these changes](https://github.com/PsiLupan/melee/compare/09494419968e7a0aefaca91b023a867e43550c97..ribbanya:melee:wip/robj)?
- Restore all of `robj.s`
- Unlink `robj.c`
- Replace inline asm with `NOT_IMPLEMENTED` in `robj.c`
- Tweak your change to `object.h` to be the correct macro usage
- Revert your change to `jobj.h` because it wasn't matching
- objdiff looks like this:
  image

**Comment by PsiLupan** [comment]
That's fine.

I was mostly intended for this to stick around till I finished RObj
completely - just having this as a means of showing this is worked on
already.

**Comment by ribbanya** [comment]
Okay, up to you.

**Comment by PsiLupan** [comment]
I'd say go ahead. If I get around to matching the few remaining functions,
I'll handle getting the file matching from the DTK setup.

**Pull request merged**
